#!/usr/bin/env python3
import files
import sys
import random

# explaining here what I would like to do so that i can once again arrange my thoughts
"""
The .ftx file format was designed to facilitate simple data storage and handling for the SABR project, however
its utility means that it will likely outrange it in usage. To that end, and to better exhibit the virtue of 
'one tool, one purpose', this script and collection of modules will seek to process FTXs and parse their data
to be used in downstream analysis. By making the steps discreet, more efficient analysis can be carried out.

For now this module will likely only concern itself with the SABR project and what it is interested in. In future,
it may be useful as a diagnostic or part of a larger workflow.

Current goals:
- line by line, understand the case and results. Case is determined by ground truth, results through comparison
- generate output files, each containing the results for the isolated aspect of interest. As of right now, that includes
  unspliced, spliced, anad internal cases.

thought: need to keep track of names and it is enough for now to realize this: that you need to sleep earlier and get to campus with more time before having to go home to feed nori.
"""
def casefinder(coords, rl):
  if len(coords) < 2:
    return "unspliced"

  if len(coords) == 2:
    return "spliced"

  print(lenfinder(coords[0].split('-')), lenfinder(coords[1].split('-')))  
  if lenfinder(coords[0].split('-')) + lenfinder(coords[1].split('-')) > rl:
    return "spliced"

  return "internal"

def gapfinder(coords):
  if lenfinder(coords[-1].split('-')) > lenfinder(coords[0].split('-')):
    return "fivep"
  elif lenfinder(coords[-1].split('-')) == lenfinder(coords[0].split('-')):
    return "equal"
  else:
    return "threep"

def lenfinder(coord):
  return int(coord[1]) - int(coord[0]) + 1


def rlenfinder(coords):
  totrl = 0

  for coord in coords:
    totrl += lenfinder(coord.split('-'))

  return totrl

file = sys.argv[1]

# The file has a few fields, but realy what needs to happen is to store the information in an efficient way. two dicts? hash

gtnames = []
chroms = []
strands = []
gt_coords = []
exp_name = []
exp_chroms = []
exp_coords = []
exp_strands = []
cases = []
detected = []
correct = []
o_len = []
isize = []
warns = []

rlen = None
with files.getfp(file) as fp:
  for line in fp:
    has_MSA = False
    MSA_names = []
    warn_needed = False

    gtline, expline = line.rstrip().split()

    strands.append(gtline[-1])

    gt = gtline.split('|')

    chrom, gtname, _, gtcrd, strand = gtline.split('|')

    gtcrds = gtcrd.split(',')
    strand = strand[-1]

    # warning checks

    # MSA
    if '~' in expline:
      warn_needed = True
      has_MSA = True


    explines = expline.split("~")
    for expl in explines:
      print(expl)
      if expl != "None":
        if expl.endswith('|'): expl = expl[0:-1]
        echrom, ename, estrand, ecrd = expl.split('|')


      else:
        echrom, ename, estrand, ecrd = "None", "None", "None", "None"
      

      gtnames.append(gtname)
      chroms.append(chrom)
      strands.append(strand)
      gt_coords.append(';'.join(gtcrds))
      exp_name.append(ename)
      exp_coords.append(echrom)
      exp_strands.append(estrand)

      if rlen == None:
        rlen = rlenfinder(gtcrds)

      if len(gtcrds) > 2:
        print(gtcrd)
        print(casefinder(gtcrds, rlen))
        if random.random() < 0.0000010:
          break

    if not warn_needed:
      warns.append("-")
      continue

    if has_MSA:
      for name in MSA_names:
        warns.append("Part of an MSA. Other members:", ";".join(MSA_names))

    if len(warns) != len(gtnames):
      print(len(warns), len(gtnames))

